version: "3.7"

services:
  # flask
  flask:
    build:
      context: ./bin/flask
    image: sashuu6/flask_mongodb:flask
    container_name: "sashuu6-flask_mongo-flask"
    restart: "always"
    ports:
      - "${flaskport}:5000"
    working_dir: /usr/share/sampleFlask/
    environment:
      FLASK_ENV: ${flaskENV}
    links:
      - mongodb
    volumes:
      - ${LOG_FILE-./logs/flask/}:/usr/share/sampleFlask/logs/

  # MongoDB
  mongodb:
    build:
      context: ./bin/mongodb
    image: sashuu6/flask_mongodb:mongodb
    container_name: "sashuu6-flask_mongo-mongodb"
    restart: "always"
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${MONGODB_DATA_DIR-./data/mongodb}:/data/db
      - ${MONGODB_CONFIG_DIR-./config/mongodb/mongod.conf}:/etc/mongo/mongod.conf
      - ${MONGODB_LOG_DIR-./logs/mongodb/}:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    command: --config /etc/mongo/mongod.conf

  # Mongo Express
  mongo-express:
    build:
      context: ./bin/mongo-express
    image: sashuu6/flask_mongodb:mongo-express
    container_name: "sashuu6-flask_mongo-mongo_express"
    restart: always
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
